server:
  port: 8080

spring:
  application:
    name: news-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/news_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://auth-service:8081
