server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ruslan2808/config-server.git
          default-label: master
          search-paths: news-management-system
